name: Build Linux
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgl-dev clang cmake
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mkdir -p tmp/bin tmp/include tmp/lib tmp/licenses
      - run: make -f Makefile.linux.mk
      - run: ./make_sdl.sh
      - run: ./make_sdl_image.sh
      - run: ./make_sdl_mixer.sh
      - run: ./pack.sh
      - name: Upload libs
        uses: svenstaro/upload-release-action@2.4.1
        with:
          file: tmp/SDL-linux-binary.tgz
          asset_name: SDL-linux-binary-${{github.ref_name}}.tgz
          overwrite: true
